export const helpCommand = {
  name: 'help',
  aliases: [],
  description: 'show clara commands',
  options: [],

  async prefix({ message }) {
    await message.reply(
      [
        '╭───── clara',
        '│',
        '│  utility',
        '│  ├─ .avatar @user  •  .av @user',
        '│  ├─ .serverinfo  •  .si',
        '│  ├─ .banner @user',
        '│  ├─ .serverbanner',
        '│  ├─ .servericon',
        '│  ├─ .nickname @user [name]',
        '│  └─ .nick @user [name]',
        '│',
        '│  moderation',
        '│  ├─ .ban @user reason',
        '│  ├─ .kick @user reason',
        '│  ├─ .timeout @user 10min',
        '│  ├─ .purge 10',
        '│  ├─ .lock  •  .unlock',
        '│  ├─ .hide  •  .unhide',
        '│  ├─ .nuke',
        '│  └─ .role @user rolename',
        '│',
        '│  roles',
        '│  ├─ .role rolename',
        '│  ├─ .role create rolename',
        '│  └─ .role delete rolename',
        '│',
        '│  misc',
        '│  ├─ .remindme 2min reason',
        '│  └─ .echo message',
        '│',
        '│  reminder time',
        '│  ├─ s / sec  → seconds',
        '│  ├─ m / min  → minutes',
        '│  ├─ h / hr   → hours',
        '│  └─ d        → days',
        '│',
        '╰───── clara',
      ].join('\n'),
    );
  },

  async slash({ interaction }) {
    await interaction.reply(
      [
        '╭───── clara',
        '│',
        '│  utility',
        '│  ├─ /avatar  •  /av',
        '│  ├─ /serverinfo  •  /si',
        '│  ├─ /banner',
        '│  ├─ /serverbanner',
        '│  ├─ /servericon',
        '│  ├─ /nickname  •  /nick',
        '│',
        '│  moderation',
        '│  ├─ /ban',
        '│  ├─ /kick',
        '│  ├─ /timeout',
        '│  ├─ /purge',
        '│  ├─ /lock  •  /unlock',
        '│  ├─ /hide  •  /unhide',
        '│  ├─ /nuke',
        '│  └─ /role',
        '│',
        '│  misc',
        '│  ├─ /remindme',
        '│  └─ /echo',
        '│',
        '╰───── clara',
      ].join('\n'),
    );
  },
};