export const helpCommand = {
  name: 'help',
  aliases: [],
  description: 'show clara commands',
  options: [],

  async prefix({ message }) {
    await message.reply(
      [
        'utilities:',
        '.avatar / .av @user',
        '.serverinfo / .si',
        '.banner @user',
        '.serverbanner',
        '.servericon',
        '.nickname / .nick @user [name]',
        '.remindme 2min reason',
        '.echo message',
        '',
        'moderation:',
        '.ban @user reason',
        '.kick @user reason',
        '.timeout @user 10min',
        '.purge 10',
        '.lock',
        '.unlock',
        '.hide',
        '.unhide',
        '.nuke',
        '.role @user rolename',
        '.role rolename',
        '.role create rolename',
        '.role delete rolename',
      ].join('\n'),
    );
  },

  async slash({ interaction }) {
    await interaction.reply(
      [
        'utilities:',
        '/avatar',
        '/av',
        '/serverinfo',
        '/si',
        '/banner',
        '/serverbanner',
        '/servericon',
        '/nickname',
        '/nick',
        '/remindme',
        '/echo',
        '',
        'moderation:',
        '/ban',
        '/kick',
        '/timeout',
        '/purge',
        '/lock',
        '/unlock',
        '/hide',
        '/unhide',
        '/nuke',
        '/role',
      ].join('\n'),
    );
  },
};