const nicknameMessages = [
  'there, identity crisis solved.',
  'new name, new problems.',
  'consider it done.',
  'there. much better.',
  'nickname updated.',
  'done. your rebrand is complete.',
  'new nickname installed.',
  'name changed. dignity pending.',
  'tiny rebrand complete.',
  'done. try not to ruin it.',
  'nickname makeover complete.',
  'there you go.',
  'new identity unlocked.',
  'name update successful.',
  'done. moving on.',
  'nickname operation complete.',
  'fresh name applied.',
  'the rebrand is official.',
  'nickname successfully changed.',
  'that should do it.',
  'new name detected.',
  'all sorted.',
  'the old nickname is gone.',
  'your rebrand is complete.',
  'name change confirmed.',
  'nickname successfully replaced.',
  'done. surprisingly easy.',
  'profile refreshed.',
  'new nickname is live.',
  'there. problem solved.',
  'name adjusted accordingly.',
  'done. no further questions.',
  'nickname update accepted.',
  'clean little rename.',
  'new name secured.',
  'rebrand finalized.',
  'nickname switched.',
  'name successfully updated.',
  'done. onward.',
  'your nickname got a refresh.',
  'new label applied.',
  'rename complete.',
  'nickname change confirmed.',
  'done. simple enough.',
  'old name archived.',
  'new nickname applied.',
  'your server identity has changed.',
  'name update completed.',
  'nickname modified successfully.',
  'there. all fixed.',
  'new name locked in.',
  'nickname refreshed.',
  'rebrand accepted.',
  'done. quite painless.',
  'your profile just changed.',
  'nickname operation successful.',
  'name change successful.',
  'new nickname secured.',
  'the rename is complete.',
  'done. looking official.',
  'nickname successfully altered.',
  'fresh nickname incoming.',
  'name successfully changed.',
  'there. clean and simple.',
  'the new name is active.',
  'nickname updated without drama.',
  'done. next.',
  'your name has been rewritten.',
  'rebrand completed.',
  'nickname update finished.',
  'new name applied successfully.',
  'there. enjoy the change.',
  'name successfully reset.',
  'nickname reset complete.',
  'back to your original name.',
  'the old name is back.',
  'nickname restored.',
  'original name restored.',
  'reset complete.',
  'there. back to normal.',
  'your nickname has been cleared.',
  'nickname removed.',
  'name reset successfully.',
  'back to default.',
  'default nickname restored.',
  'clean slate.',
  'nickname cleared.',
  'original name is back.',
  'reset successful.',
  'there. fresh start.',
  'your nickname has been reset.',
  'name restored.',
  'nickname back to default.',
  'reset and done.',
  'the custom name is gone.',
  'original identity restored.',
  'nickname returned to normal.',
  'default name restored.',
];

export function randomNicknameMessage() {
  return nicknameMessages[
    Math.floor(Math.random() * nicknameMessages.length)
  ];
}